BE14-NoB/pick-frontend

package-lock.json, pick-front/src/App.vue, pick-front/src/components/MyFooter.vue
- 기존거에서 수정
- 각 요청 경로는 반영후 수정할 예정
=> [Feature] 푸터 / 푸터 컴포넌트 제작

pick-front/index.html, pick-front/src/components/member/MemberInfo.vue
refactor/sy/member/info -> main
close #이슈번호
close #18 
----
=> refactor: 회원 정보 페이지 수정

pick-front/src/components/MyFooter.vue, pick-front/src/components/MyHeader.vue, pick-front/src/components/post/PostList.vue, pick-front/src/components/post/SearchBox.vue, pick-front/src/components/post/SideBar.vue, pick-front/src/components/post/SinglePost.vue, pick-front/src/router/router.js, pick-front/src/views/PostView.vue
feature/cm/post/enhancingSearchBox
close #27 
----
=> [Feat] 검색창 고도화

pick-front/src/components/project/ProjectLayout.vue, pick-front/src/components/project/ProjectSidebar.vue, pick-front/src/components/project/ProjectTabs.vue
Design/sh/project/common -> main
close #29 
- 프로젝트 공용 페이지 디자인 수정
=> [Design] proeject / 프로젝트 공용 페이지 디자인 수정

pick-front/src/components/member/MemberInfo.vue, pick-front/src/components/member/MemberProfile.vue
feature/sy/member/profie -> main
close #이슈번호
----
=> feat: 회원 프로필 추가

pick-front/src/components/project/ProjectLayout.vue, pick-front/src/data/project/MenuData.js, pick-front/src/router/router.js, pick-front/src/views/project/dashboard/DashboardView.vue
close #이슈번호
- 레이아웃에서 대시보드 컴포넌트 보이도록 수정
----
=> [Refactor] 프로젝트 레이아웃 수정

pick-front/src/components/member/MemberProfile.vue
=> refactor: 회원 프로필 입력란 수정

pick-front/src/components/common/MyHeader.vue, pick-front/src/components/member/MemberSignUp.vue, pick-front/src/router/router.js
feature/sy/member/signup
close #이슈번호
close #45  
📄 설명
현재는 확인 편의를 위해서 회원가입에다가 로그인 라우팅 해놓은 상태
회원가입 버튼 누를시 로그인 창 으로 이동 기본 틀 구현
✅ 작업할 내용
스타일 바꾸기
메인페이지 위에 팝업으로 뜨게 하기
전체적인 모양 수정
----
=> [feature] 회원 로그인 기능 추가

pick-front/src/components/common/MyHeader.vue
feature/sy/member/logout -> main
close #이슈번호
close #49 
- 프로필 클릭 후 드롭다운에서 로그아웃 누를시 메인페이지 이동 및 헤더 로그인 전상태로 경
----
=> feat: 로그아웃 추가

pick-front/src/components/common/MyHeader.vue, pick-front/src/components/member/MemberSignUp.vue, pick-front/src/router/router.js
feature/sy/member/signup-modal -> main
close #이슈번호
close #51 
- 회원가입 버튼 누를시 회원가입 모달 창 뜨고, 회원가입 누를시 메인페이지 이동 및 헤더 로그인 전상태로 이동
- 텍스트필드 정렬할 예정
----
=> feat : 회원가입 모달 추가

pick-front/src/components/Pagination.vue, pick-front/src/json/project_issuelist.json, pick-front/src/views/project/issue/IssueList.vue
refactor/hm/project/refactorIssueList -> main
close #55 
* 프로젝트 페이지 레이아웃 적용
* 프로젝트 탭 적용
* 이슈 open/close 구분
=> [Refactor] 이슈 목록 조회 페이지 개선

pick-front/src/components/member/MemberSignUp.vue
refactor/sy/member/signup/validation -> main
close #이슈번호
close #57 
유효성 검사 추가
----
=> feat : 유효성 검사 및 기본 폼 작성

pick-front/src/json/project_prlist.json, pick-front/src/views/project/pr/PRListView.vue
feature/hm/project/createPRList
close #59 
* 프로젝트 컴포넌트 적용
* json 파일 생성
=> [Feature] PR 조회 페이지 생성

pick-front/src/components/project/PRCreateButton.vue, pick-front/src/views/project/pr/PRListView.vue
refactor/hm/project/refactorPRList -> main
close #62 
* PR 생성하기 버튼 추가
=> [Refactor] PR 조회  페이지에 PR 생성하기 버튼 추가

pick-front/src/json/project_commitlist.json, pick-front/src/json/project_prlist.json, pick-front/src/views/project/commit/CommitListView.vue, pick-front/src/views/project/pr/PRListView.vue
feature/hm/project/createCommitListView -> main
close #64 
* 커밋 내역 조회 페이지 생성
=> [Feature] 커밋 내역 조회 페이지 생성

pick-front/src/components/MemberSideBar.vue, pick-front/src/components/dailymission/components/ProgressBar.vue, pick-front/src/components/dailymission/components/TodayDate.vue, pick-front/src/components/dailymission/views/DailyMission.vue, pick-front/src/json/dailymission.json
refactor/hm/dailymission/createdailymission -> main
close #66 
* 일일미션 페이지 수정
* 회원 관련 페이지 사이드바 수정
=> [Refactor] 일일미션 페이지 수정

pick-front/src/components/MemberSideBar.vue
refactor/hm/member/modifySidebar -> main
close #73 
* 멤버 사이드바 수정(선택 상태 고정)
=> [Refactor] 멤버 사이드바 수정

pick-front/src/components/post/PostList.vue, pick-front/src/components/post/SinglePost.vue
feature/cm/post/paginationHotfix -> main
Pagination.vue 경로 변경 반영
=> [Hotfix] post / 페이지네이션 경로 변경 반영

pick-front/src/components/project/PRCreateButton.vue
refactor/hm/project/refactorRoot -> main
close #90 
* PR 생성 버튼 클릭 시 이동 경로 변경
=> [Refactor] PR 생성 버튼 클릭 시 이동 경로 변경

pick-front/src/components/matching/MatchingCreate.vue, pick-front/src/components/matching/MatchingSearch.vue, pick-front/src/components/matching/MatchingSideBar.vue
siwon -> main
close #92 
- 매칭 생성 모달 창(추후 수정 예정)
----
=> [Feature] 매칭 생성 모달창

pick-front/src/components/member/MemberProfile.vue
refactor/sy/member/image -> main
close #이슈번호
close #95 
- 사진 불러오기 가능
----
=> [refactor] 회원 프로필 사진 수정

pick-front/src/components/MemberSideBar.vue, pick-front/src/components/common/MyHeader.vue
refactor/sy/member/dashboard -> main
close #이슈번호
close #99 
- 사이드바 및 헤더에 진행중인 프로젝트 라우팅 연결하여 대쉬보드 들어갈 수 있게 변경
----
=> refactor : 라우팅 수정

pick-front/src/components/project/pr/PRCommitList.vue
design/sh/pr/review -> main
close #이슈번호
- PR리뷰 페이지 '이름 + 아바타'에서 '아바타 + 이름'으로 수정
=> [Design] PR 리뷰 페이지 수정

pick-front/src/components/common/MyHeader.vue, pick-front/src/components/member/MemberSignUp.vue
refactor/sy/member/button -> main
close #이슈번호
- 닫기 버튼 위치 수정
- 가입하기 버튼 2배 키움
----
=> refactor : 모달 관련 수정 완료

pick-front/src/json/project_commitlist.json, pick-front/src/views/project/commit/CommitListView.vue
refactor/hm/refactor/commitList -> main
close #이슈번호
* 회원별 프로필 사진 변경
=> [Refactor] 커밋 목록 조회 페이지 수정

pick-front/src/json/post_list.json
feature/cm/post/commentNumSyncNAddDummy -> main
close #이슈번호
=> [Feat] post / 누락된 더미 데이터 추가

pick-front/src/components/common/MyFooter.vue
feature/sy/footer
close #이슈번호
close #119 
- 푸터 라우팅 연결, 지원 안되는 기능에 대해서는 팝업창으로 접근 안되게 설정
----
=> feat: 푸터 라우팅 연결

pick-front/src/json/reviews.json
refactor/sy/member/json -> main
close #이슈번호
close #130 
- 프로젝트 기준으로 사용자 닉네임 통일
----
=> refactor: 회원 후기 닉네임 정정

pick-front/src/components/matching/MatchingResult.vue
siwon -> main
close #이슈번호
- 매칭 로딩 로직 오타 수정
----
=> [Refactor] 매칭 로딩 로직 오타 수정

pick-front/src/components/post/CommentItem.vue, pick-front/src/components/post/CommentList2.vue, pick-front/src/components/post/SinglePost.vue
feature/cm/post/childComment -> main
close #139
대댓글 들여쓰기 된 채로 표시되도록 구현
=> [Feat] post / 대댓글 표시되도록 구현

pick-front/src/components/post/PostList.vue, pick-front/src/components/post/SinglePost.vue
design/cm/post/searchBoxNButtonAlign -> main
close #이슈번호
=> [Design] post / 검색창과 글쓰기 버튼 정렬

pick-front/src/views/project/issue/IssueList.vue
feature/sh/git/issueList
close #이슈번호
- 이슈 리스트 깃 API 연동
=> [Feat] git / 이슈 리스트 깃 API 연동

pick-front/src/components/project/MeetingWidget.vue, pick-front/src/components/project/member/MemberReviewModal.vue, pick-front/src/json/project_entry.json, pick-front/src/views/project/member/ProjectMemberView.vue
-  @[x] 버그 픽스
close #이슈번호
----
=> [Refactor] 프로젝트 관련 위젯 수정

pick-front/src/components/MemberSideBar.vue, pick-front/src/components/matching/CompletedProject.vue, pick-front/src/router/router.js
siwon -> main
close #이슈번호
- 사이드바 선택중인 항목 css 적용되게 수정
----
=> [Refactor] 멤버 사이드바 css 적용되게 수정

pick-front/src/components/matching/CompletedProject.vue, pick-front/src/components/member/MemberProfile.vue
siwon -> main
close #이슈번호
프로필 더보기 버튼 활성화
----
=> [Refactor] 프로필 더보기 버튼 활성화
